import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:dev_quotes/core/theme/colors.dart';
import '../../../../../core/providers.dart';
import '../../../../../core/services/notifications/notification_service.dart';
import '../../../../../core/utils/type_defs.dart';
import '../../../../../data/models/quote_model.dart';
import '../../../../auth/controllers/auth_controller.dart';
import '../../../../auth/models/auth_state.dart';
import '../../../../quotes/presentation/providers/quote_provider.dart';

class AddQuoteScreen extends ConsumerStatefulWidget {
  const AddQuoteScreen({super.key});

  @override
  ConsumerState<AddQuoteScreen> createState() => _AddQuoteScreenState();
}

class _AddQuoteScreenState extends ConsumerState<AddQuoteScreen> {
  final _quoteController = TextEditingController();
  final _authorController = TextEditingController();
  String? _selectedCategory;
  bool _isLoading = false;
  @override
  void initState() {
    super.initState();
    // Pre-fill author with user's name
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final authAsync = ref.read(authProvider);
      final authState = authAsync.value;
      if (authState is AuthAuthenticated) {
        _authorController.text = authState.user.username;
      }
    });
  }

  @override
  void dispose() {
    _quoteController.dispose();
    _authorController.dispose();
    super.dispose();
  }

  void _showSnackBar(String message, {bool isError = false}) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError
            ? const Color(0xFFFF453A)
            : const Color(0xFF34C759),
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
        duration: const Duration(seconds: 2),
      ),
    );
  }

  Future<void> _submitQuote() async {
    // Validation
    if (_quoteController.text.trim().isEmpty) {
      _showSnackBar('Please enter the quote text', isError: true);
      return;
    }

    if (_selectedCategory == null) {
      _showSnackBar('Please select a category', isError: true);
      return;
    }

    final authAsync = ref.read(authProvider);
    final authState = authAsync.value;
    if (authState is! AuthAuthenticated) {
      _showSnackBar('You must be logged in to add quotes', isError: true);
      return;
    }

    setState(() => _isLoading = true);

    try {
      final quoteRepo = ref.read(quoteRepositoryProvider);
      final newQuote = Quote(
        id: '', // Will be generated by Firestore
        text: _quoteController.text.trim(),
        author: _authorController.text.trim(),
        category: _selectedCategory!,
        userId: authState.user.id,
        timestamp: DateTime.now(),
        isFavorite: false,
      );

      final result = await quoteRepo.addQuote(newQuote);

      if (result is Success<String>) {
        final quoteId = result.data;
        // Send notification
        await NotificationService().sendNewQuoteNotification(
          quoteId,
          newQuote.text,
          newQuote.author,
          authState.user.id,
        );

        // Clear form first
        _quoteController.clear();
        setState(() => _selectedCategory = null);

        // Show success notification
        _showSnackBar('Quote added successfully!');

        // Navigate back after showing the notification
        Future.delayed(const Duration(seconds: 2), () {
          if (mounted) context.pop();
        });
      } else if (result is Error<String>) {
        _showSnackBar(result.failure.message, isError: true);
      }
    } catch (e) {
      _showSnackBar('Error: ${e.toString()}', isError: true);
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final categoriesAsync = ref.watch(categoriesProvider);

    return Scaffold(
      backgroundColor: const Color(0xFF0F0F13),
      appBar: AppBar(
        backgroundColor: const Color(0xFF0F0F13),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => context.pop(),
        ),
        title: Text(
          'Add Quote',
          style: GoogleFonts.outfit(
            color: Colors.white,
            fontWeight: FontWeight.w600,
          ),
        ),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildLabel('Quote Text'),
            const SizedBox(height: 8),
            TextFormField(
              controller: _quoteController,
              maxLines: 5,
              style: GoogleFonts.inter(color: Colors.white),
              decoration: _buildInputDecoration(
                'Enter the inspiring quote here...',
              ),
            ),
            const SizedBox(height: 24),
            _buildLabel('Author'),
            const SizedBox(height: 8),
            TextFormField(
              controller: _authorController,
              readOnly: true,
              style: GoogleFonts.inter(color: Colors.white),
              decoration: _buildInputDecoration('Author\'s Name'),
            ),
            const SizedBox(height: 24),
            _buildLabel('Category'),
            const SizedBox(height: 8),
            _buildCategorySelector(categoriesAsync),
            const SizedBox(height: 40),
            SizedBox(
              width: double.infinity,
              height: 56,
              child: Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(12),
                  boxShadow: [
                    BoxShadow(
                      color: const Color(0xFF8B5CF6).withOpacity(0.3),
                      blurRadius: 12,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _submitQuote,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF8B5CF6),
                    disabledBackgroundColor: const Color(
                      0xFF8B5CF6,
                    ).withOpacity(0.5),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    elevation: 0,
                  ),
                  child: _isLoading
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            valueColor: AlwaysStoppedAnimation<Color>(
                              Colors.white,
                            ),
                          ),
                        )
                      : Text(
                          'Submit Quote',
                          style: GoogleFonts.inter(
                            fontSize: 16,
                            fontWeight: FontWeight.w600,
                            color: Colors.white,
                          ),
                        ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCategorySelector(AsyncValue<List<String>> categoriesAsync) {
    return categoriesAsync.when(
      data: (categories) => GestureDetector(
        onTap: () => _showCategoryPicker(context, categories),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
          decoration: BoxDecoration(
            color: const Color(0xFF1E1E24),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: Colors.white.withOpacity(0.05)),
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                _selectedCategory ?? 'Select Category',
                style: GoogleFonts.inter(
                  color: _selectedCategory != null
                      ? Colors.white
                      : Colors.grey[600],
                  fontSize: 16,
                ),
              ),
              const Icon(Icons.keyboard_arrow_down_rounded,
                  color: Colors.white),
            ],
          ),
        ),
      ),
      loading: () => const Padding(
        padding: EdgeInsets.all(12),
        child: LinearProgressIndicator(color: Color(0xFF8B5CF6)),
      ),
      error: (err, stack) => Text(
        'Failed to load categories',
        style: GoogleFonts.inter(color: AppColors.error),
      ),
    );
  }

  void _showCategoryPicker(BuildContext context, List<String> categories) {
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      builder: (context) => Container(
        height: MediaQuery.of(context).size.height * 0.7,
        decoration: const BoxDecoration(
          color: Color(0xFF16161D),
          borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
        ),
        child: Column(
          children: [
            Container(
              margin: const EdgeInsets.only(top: 12, bottom: 24),
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.1),
                borderRadius: BorderRadius.circular(2),
              ),
            ),
            Text(
              'Select Category',
              style: GoogleFonts.outfit(
                color: Colors.white,
                fontSize: 20,
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(height: 24),
            Expanded(
              child: ListView.separated(
                padding: const EdgeInsets.all(24),
                itemCount: categories.length,
                separatorBuilder: (_, __) => const SizedBox(height: 12),
                itemBuilder: (context, index) {
                  final category = categories[index];
                  final isSelected = category == _selectedCategory;
                  return Material(
                    color: Colors.transparent,
                    borderRadius: BorderRadius.circular(12),
                    child: InkWell(
                      onTap: () {
                        setState(() => _selectedCategory = category);
                        Navigator.pop(context);
                      },
                      borderRadius: BorderRadius.circular(12),
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                            vertical: 16, horizontal: 20),
                        decoration: BoxDecoration(
                          color: isSelected
                              ? const Color(0xFF8B5CF6).withOpacity(0.2)
                              : const Color(0xFF1E1E24),
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(
                            color: isSelected
                                ? const Color(0xFF8B5CF6)
                                : Colors.white.withOpacity(0.05),
                          ),
                        ),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              category,
                              style: GoogleFonts.inter(
                                color: Colors.white,
                                fontSize: 16,
                                fontWeight: isSelected
                                    ? FontWeight.w600
                                    : FontWeight.w400,
                              ),
                            ),
                            if (isSelected)
                              const Icon(Icons.check_circle_rounded,
                                  color: Color(0xFF8B5CF6), size: 20),
                          ],
                        ),
                      ),
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLabel(String text) {
    return Text(
      text,
      style: GoogleFonts.inter(
        color: Colors.grey[400],
        fontSize: 14,
        fontWeight: FontWeight.w500,
      ),
    );
  }

  InputDecoration _buildInputDecoration(String hint) {
    return InputDecoration(
      hintText: hint,
      hintStyle: GoogleFonts.inter(color: Colors.grey[600]),
      filled: true,
      fillColor: const Color(0xFF1E1E24),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide.none,
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: Colors.white.withOpacity(0.05)),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: Color(0xFF8B5CF6)),
      ),
      contentPadding: const EdgeInsets.all(16),
    );
  }
}
